export const TEST_IDS = {
  BADGE_CONTAINER: 'badge-container',
  BADGE: 'badge',
  BADGE_TEXT: 'badge-text',
  HEADER_CART_BUTTON: 'header-cart-button',
  HEADER_BACK_BUTTON: 'header-back-button',
  BUTTON: 'button',
  ENHANCED_VIEW: 'enhanced-view',
  TEXT: 'text',
  FLAT_LIST: 'flat-list',
  INFINITY_SCROLL_FLAT_LIST: 'infinity-scroll-flat-list',
  CENTER: 'center',
  LIST_EMPTY_COMPONENT: 'list-empty-component',
  PRODUCT_LIST_ITEM: 'product-list-item',
  PRODUCT_LIST_ITEM_REMOVE_BUTTON: 'PRODUCT_LIST_ITEM-remove-product-button',
  PRODUCT_LIST_ITEM_ADD_BUTTON: 'PRODUCT_LIST_ITEM-add-product-button',
};
